// <auto-generated />
namespace IPAdmin.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddUnique : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddUnique));
        
        string IMigrationMetadata.Id
        {
            get { return "201404031043082_AddUnique"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
