// <auto-generated />
namespace IPAdmin.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RestrictLength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RestrictLength));
        
        string IMigrationMetadata.Id
        {
            get { return "201404031112427_RestrictLength"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
